<?php
// It's just a region for testing out code templates.
require_once('../../sirel.php');
//------------------------------------------------------------------------



class Blackboard {




// RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// s_fp_cg=ENV['SIREL_HOME']+"/src/dev_tools/code_generation"
// require(s_fp_cg+"/sirel_cg0.rb")
// #require(s_fp_cg+"/by_file/blackboard_block1.rb")
// RENESSAATOR_SOURCE_END
//
// RENESSAATOR_AUTOGENERATED_TEXT_START

// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END

}// class Blackboard

$s="[\\\"iii\\\"]";
echo $s;

$s0=mb_ereg_replace('[\\\\]"', '"', $s);
$s1=mb_ereg_replace('[\\r]', "", $s0);
echo '<br/>'.$s1;



//$bb->run();
//------------------------------------------------------------------------
?>
